// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar principal que incluye introducción general
  mainSidebar: [
    'intro'
  ],

  // Sidebar del Tema 1: Fundamentos de la Seguridad Informática y Marco Legal
  tema1Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-1-fundamentos',
    },
  ],

  // Sidebar del Tema 2: Seguridad Física y Medidas Pasivas
  tema2Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-2-seguridad-fisica',
    },
  ],

  // Sidebar del Tema 3: Gestión de Datos y Copias de Seguridad
  tema3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-3-gestion-datos',
    },
  ],

  // Sidebar del Tema 4: Amenazas Lógicas y Protección Activa
  tema4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-4-amenazas-logicas',
    },
  ],

  // Sidebar del Tema 5: Seguridad en Redes y Cortafuegos
  tema5Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-5-seguridad-redes',
    },
  ],
};

export default sidebars;
