// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar principal que incluye introducción general
  mainSidebar: [
    'intro'
  ],
  
  // Sidebar del Tema 1: Introducción a la Seguridad Informática
  tema1Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-1-introduccion',
    },
  ],
  
  // Sidebar del Tema 2: Amenazas y Vulnerabilidades
  tema2Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-2-amenazas',
    },
  ],
  
  // Sidebar del Tema 3: Criptografía
  tema3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-3-criptografia',
    },
  ],
  
  // Sidebar del Tema 4: Seguridad en Redes
  tema4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-4-seguridad-redes',
    },
  ],
  
  // Sidebar del Tema 5: Seguridad en Sistemas
  tema5Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema-5-seguridad-sistemas',
    },
  ],
};

export default sidebars;
