#!/bin/bash
# Guía de comandos Vagrant para prácticas específicas

echo "========================================="
echo "Guía de Vagrant - Prácticas del Lab SAD"
echo "========================================="

echo ""
echo "🔐 MÓDULO 2: Seguridad Física y Lógica"
echo "--------------------------------------"
echo "# Práctica básica de seguridad:"
echo "vagrant up ubuntu-server"
echo "vagrant up windows-server"
echo ""
echo "# Suspender al terminar:"
echo "vagrant suspend ubuntu-server windows-server"

echo ""
echo "🌐 MÓDULO 3: Seguridad en Redes"
echo "-------------------------------"
echo "# Análisis de tráfico y pentesting:"
echo "vagrant up ubuntu-server kali-security"
echo "vagrant up windows-server  # Si necesitas target Windows"
echo ""
echo "# Para análisis completo:"
echo "vagrant up ubuntu-server kali-security windows-server"

echo ""
echo "💾 MÓDULO 4: Copias de Seguridad"
echo "--------------------------------"
echo "# Configuración de backup:"
echo "vagrant up ubuntu-server storage-backup"
echo ""
echo "# Con cliente Windows:"
echo "vagrant up ubuntu-server storage-backup windows-client"

echo ""
echo "🔍 MÓDULO 5: Análisis Forense"
echo "-----------------------------"
echo "# Investigación completa:"
echo "vagrant up kali-security ubuntu-server"
echo "vagrant up windows-server  # Para forense Windows"
echo "vagrant up storage-backup  # Para preservar evidencias"

echo ""
echo "🏢 PRÁCTICA COMPLETA (Simulación Empresa)"
echo "----------------------------------------"
echo "# Entorno completo (requiere 8+ GB RAM):"
echo "vagrant up ubuntu-server windows-server storage-backup"
echo "vagrant up kali-security  # Para auditoría"
echo "vagrant up windows-client  # Para usuarios finales"

echo ""
echo "⚡ COMANDOS ÚTILES"
echo "----------------"
echo "# Ver estado de todas las VMs:"
echo "vagrant status"
echo ""
echo "# Conectar por SSH:"
echo "vagrant ssh ubuntu-server"
echo "vagrant ssh kali-security"
echo "vagrant ssh storage-backup"
echo ""
echo "# Suspender todo (liberar RAM):"
echo "vagrant suspend --all"
echo ""
echo "# Reanudar todo:"
echo "vagrant resume --all"
echo ""
echo "# Apagar todo:"
echo "vagrant halt --all"
echo ""
echo "# Reiniciar una VM:"
echo "vagrant reload ubuntu-server"

echo ""
echo "💡 TIPS DE GESTIÓN DE RECURSOS"
echo "-----------------------------"
echo "# 1. Usa suspend/resume en lugar de halt/up para ser más rápido"
echo "# 2. Solo levanta las VMs que necesites para cada práctica"
echo "# 3. Monitoriza la RAM: htop o Task Manager"
echo "# 4. Si tienes poca RAM, haz prácticas por módulos separados"

echo ""
echo "🚫 CUÁNDO NO USAR VAGRANT"
echo "------------------------"
echo "# Solo usa VirtualBox GUI si:"
echo "# - Vagrant no funciona por algún error"
echo "# - Necesitas cambiar configuración de hardware"
echo "# - Quieres acceso directo a consola gráfica"
echo "# - Estás haciendo debugging de la VM"